#!/bin/bash
# VPS智能优化脚本 v2.1
# 修复数组语法错误 | 增强兼容性
# 最后更新：2024-03-06

# 颜色定义
RED='\033[31m'
GREEN='\033[32m'
YELLOW='\033[33m'
BLUE='\033[34m'
RESET='\033[0m'

# 配置存储
declare -A CONFIG
CONFIG[BACKUP_DIR]="/etc/vps_optimizer_backup_$(date +%s)"
CONFIG[SSD_TYPE]=0
CONFIG[RAM_GB]=0
CONFIG[NET_DELAY]=0
CONFIG[IS_KVM]=0
CONFIG[OLD_GLIBC]=0

# 检查root权限
check_root() {
    if [[ $EUID -ne 0 ]]; then
        echo -e "${RED}错误：本脚本需要root权限执行！${RESET}"
        exit 1
    fi
}

# 检查glibc版本
check_glibc() {
    echo -e "${BLUE}[0/7] 检测glibc版本...${RESET}"
    local glibc_info=$(ldd --version 2>/dev/null | head -1)
    if [[ -z "$glibc_info" ]]; then
        echo -e "${YELLOW}警告：无法获取glibc版本，跳过检查${RESET}"
        CONFIG[GLIBC_VERSION]="unknown"
        return
    fi
    CONFIG[GLIBC_VERSION]=$(echo "$glibc_info" | grep -oE '[0-9]+\.[0-9]+' | head -1)
    local version_num=$(echo ${CONFIG[GLIBC_VERSION]} | awk -F. '{printf "%d%02d", $1, $2}')
    [[ $version_num -lt 228 ]] && CONFIG[OLD_GLIBC]=1
    echo -e "glibc版本：${GREEN}${CONFIG[GLIBC_VERSION]}${RESET}"
}

# 备份配置
backup_files() {
    echo -e "${BLUE}[1/7] 备份系统配置到 ${CONFIG[BACKUP_DIR]}...${RESET}"
    mkdir -p "${CONFIG[BACKUP_DIR]}"
    cp /etc/sysctl.conf "${CONFIG[BACKUP_DIR]}/sysctl.conf.bak"
    cp /etc/security/limits.conf "${CONFIG[BACKUP_DIR]}/limits.conf.bak"
    if [ -f /etc/default/grub ]; then
        cp /etc/default/grub "${CONFIG[BACKUP_DIR]}/grub.bak"
    fi
}

# 硬件检测
detect_hardware() {
    echo -e "${BLUE}[2/7] 检测硬件配置...${RESET}"
    CONFIG[RAM_GB]=$(free -g | awk '/Mem:/ {print $2}')
    [[ "${CONFIG[RAM_GB]}" -eq 0 ]] && CONFIG[RAM_GB]=1
    local rota_val=$(lsblk -d -o rota 2>/dev/null | awk 'NR==2 {print $1}')
    if [[ "$rota_val" == "0" ]]; then
        CONFIG[SSD_TYPE]=1
        echo -e "存储类型：${GREEN}SSD/NVMe${RESET}"
    else
        echo -e "存储类型：${YELLOW}HDD${RESET}"
    fi
    if command -v systemd-detect-virt >/dev/null 2>&1; then
        if [[ "$(systemd-detect-virt)" == "kvm" ]]; then
            CONFIG[IS_KVM]=1
            echo -e "虚拟化：${GREEN}KVM${RESET}"
        else
            echo -e "虚拟化：${YELLOW}非KVM${RESET}"
        fi
    else
        echo -e "${YELLOW}警告：无法检测虚拟化类型${RESET}"
    fi
    local kernel_ver=$(uname -r | awk -F '-' '{print $1}')
    CONFIG[KERNEL_MAJOR]=$(echo "$kernel_ver" | cut -d. -f1)
    CONFIG[KERNEL_MINOR]=$(echo "$kernel_ver" | cut -d. -f2)
    echo -e "内核版本：${GREEN}$kernel_ver${RESET}"
}

# 网络分析
analyze_network() {
    echo -e "${BLUE}[3/7] 分析网络环境...(10秒)${RESET}"
    CONFIG[NET_DELAY]=$(ping -c 4 1.1.1.1 | awk -F '/' '/rtt/ {print $5}' | cut -d. -f1)
    [[ -z "${CONFIG[NET_DELAY]}" ]] && CONFIG[NET_DELAY]=100
    echo -e "网络延迟：${GREEN}${CONFIG[NET_DELAY]} ms${RESET}"
}

# 应用优化
apply_optimizations() {
    echo -e "${BLUE}[4/7] 应用优化配置...${RESET}"
    local tcp_rmem="4096 $((16*1024)) $((CONFIG[RAM_GB]*1024*1024))"
    local tcp_wmem="4096 $((16*1024)) $((CONFIG[RAM_GB]*1024*512))"
    local udp_mem="$((CONFIG[RAM_GB]*2048)) $((CONFIG[RAM_GB]*4096)) $((CONFIG[RAM_GB]*8192))"
    
    # 生成sysctl配置
    cat > /etc/sysctl.conf <<EOF
# Generated by VPS Optimizer
net.core.rmem_max = $((CONFIG[RAM_GB]*1024*1024))
net.core.wmem_max = $((CONFIG[RAM_GB]*1024*512))
net.ipv4.tcp_rmem = $tcp_rmem
net.ipv4.tcp_wmem = $tcp_wmem
net.ipv4.tcp_window_scaling = 1
net.ipv4.tcp_sack = 1
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_fin_timeout = 30
net.core.netdev_max_backlog = $((CONFIG[RAM_GB]*2048))
net.core.somaxconn = 65535
net.ipv4.tcp_max_syn_backlog = 65535
net.ipv4.udp_mem = $udp_mem
vm.swappiness = 10
vm.dirty_ratio = 15
net.ipv4.tcp_syncookies = 1
EOF

    # 拥塞控制
    if [[ ${CONFIG[NET_DELAY]} -gt 100 ]]; then
        echo "net.core.default_qdisc = fq" >> /etc/sysctl.conf
        echo "net.ipv4.tcp_congestion_control = bbr" >> /etc/sysctl.conf
        echo "net.ipv4.tcp_notsent_lowat = 16384" >> /etc/sysctl.conf
        [[ ${CONFIG[OLD_GLIBC]} -eq 0 ]] && echo "net.ipv4.tcp_ecn = 1" >> /etc/sysctl.conf
    else
        echo "net.ipv4.tcp_congestion_control = cubic" >> /etc/sysctl.conf
        echo "net.ipv4.tcp_fastopen = 3" >> /etc/sysctl.conf
    fi

    # 内核增强
    if [[ ${CONFIG[KERNEL_MAJOR]} -ge 5 ]] || [[ ${CONFIG[KERNEL_MAJOR]} -eq 4 && ${CONFIG[KERNEL_MINOR]} -ge 13 ]]; then
        echo "net.ipv4.tcp_invalid_ratelimit = 1000000" >> /etc/sysctl.conf
    fi

    # 文件描述符
    sed -i '/^* soft nofile/d' /etc/security/limits.conf
    echo "* soft nofile 65535" >> /etc/security/limits.conf
    echo "* hard nofile 65535" >> /etc/security/limits.conf

    # 动态检测主磁盘设备名
    local main_disk=$(lsblk -nd -o NAME | head -n1)
    local disk_scheduler="deadline"
    [[ ${CONFIG[SSD_TYPE]} -eq 1 ]] && disk_scheduler="noop"
    if [[ -e "/sys/block/$main_disk/queue/scheduler" ]]; then
        grep -q 'nvme' "/sys/block/$main_disk/queue/scheduler" 2>/dev/null && disk_scheduler="none"
        echo "$disk_scheduler" > "/sys/block/$main_disk/queue/scheduler"
    fi

    sysctl -p >/dev/null
}

# 完成提示
show_result() {
    echo -e "${GREEN}[5/7] 优化完成！${RESET}"
    echo -e "验证命令："
    echo -e "  ${BLUE}sysctl net.ipv4.tcp_congestion_control${RESET}"
    echo -e "  ${BLUE}ss -tin${RESET}"
    echo -e "备份位置：${YELLOW}${CONFIG[BACKUP_DIR]}${RESET}"
}

# 主流程
main() {
    check_root
    check_glibc
    backup_files
    detect_hardware
    analyze_network
    apply_optimizations
    show_result
}

main
exit 0